"""update normalizeflag and importfileName to rawdatatable migrations

Revision ID: 035947e4320e
Revises: ce7d780c27a0
Create Date: 2026-05-21 17:03:47.920271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035947e4320e'
down_revision: Union[str, Sequence[str], None] = 'ce7d780c27a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LazadaMaster', sa.Column('ImportFileName', sa.Unicode(length=500), nullable=True))
    op.add_column('LazadaMaster', sa.Column('IsNormalized', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('LazadaMaster', sa.Column('NormalizedOn', sa.DateTime(), nullable=True))
    op.add_column('LazadaMaster', sa.Column('NormalizeError', sa.Unicode(length=2000), nullable=True))
    op.add_column('ShopeeMaster', sa.Column('ImportFileName', sa.Unicode(length=500), nullable=True))
    op.add_column('ShopeeMaster', sa.Column('IsNormalized', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('ShopeeMaster', sa.Column('NormalizedOn', sa.DateTime(), nullable=True))
    op.add_column('ShopeeMaster', sa.Column('NormalizeError', sa.Unicode(length=2000), nullable=True))
    op.add_column('TiktokMaster', sa.Column('ImportFileName', sa.Unicode(length=500), nullable=True))
    op.add_column('TiktokMaster', sa.Column('IsNormalized', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('TiktokMaster', sa.Column('NormalizedOn', sa.DateTime(), nullable=True))
    op.add_column('TiktokMaster', sa.Column('NormalizeError', sa.Unicode(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TiktokMaster', 'NormalizeError')
    op.drop_column('TiktokMaster', 'NormalizedOn')
    op.drop_column('TiktokMaster', 'IsNormalized')
    op.drop_column('TiktokMaster', 'ImportFileName')
    op.drop_column('ShopeeMaster', 'NormalizeError')
    op.drop_column('ShopeeMaster', 'NormalizedOn')
    op.drop_column('ShopeeMaster', 'IsNormalized')
    op.drop_column('ShopeeMaster', 'ImportFileName')
    op.drop_column('LazadaMaster', 'NormalizeError')
    op.drop_column('LazadaMaster', 'NormalizedOn')
    op.drop_column('LazadaMaster', 'IsNormalized')
    op.drop_column('LazadaMaster', 'ImportFileName')
    # ### end Alembic commands ###
