"""add sales value to platform order

Revision ID: 33242f79655a
Revises: 035947e4320e
Create Date: 2026-05-25 16:34:18.004584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33242f79655a'
down_revision: Union[str, Sequence[str], None] = '035947e4320e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PlatformOrder', sa.Column('SalesValue', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PlatformOrder', 'SalesValue')
    # ### end Alembic commands ###
