from sqlalchemy import Boolean, Column, DateTime, Integer, Unicode, text

from config import database as db


class LazadaMaster(db.Base):
    __tablename__ = "LazadaMaster"

    LazadaMasterId = Column(Integer, primary_key=True, autoincrement=True)

    OrderItemId = Column(Unicode(200), nullable=True)
    OrderType = Column(Unicode(200), nullable=True)
    Guarantee = Column(Unicode(200), nullable=True)
    DeliveryType = Column(Unicode(200), nullable=True)
    LazadaId = Column(Unicode(200), nullable=True)
    SellerSku = Column(Unicode(300), nullable=True)
    LazadaSku = Column(Unicode(300), nullable=True)
    Warehouse = Column(Unicode(300), nullable=True)
    CreateTime = Column(Unicode(100), nullable=True)
    UpdateTime = Column(Unicode(100), nullable=True)
    RtsSla = Column(Unicode(100), nullable=True)
    TtsSla = Column(Unicode(100), nullable=True)
    OrderNumber = Column(Unicode(200), nullable=True)
    InvoiceRequired = Column(Unicode(100), nullable=True)
    InvoiceNumber = Column(Unicode(200), nullable=True)
    DeliveredDate = Column(Unicode(100), nullable=True)
    CustomerName = Column(Unicode(300), nullable=True)
    CustomerEmail = Column(Unicode(300), nullable=True)
    NationalRegistrationNumber = Column(Unicode(300), nullable=True)
    ShippingName = Column(Unicode(300), nullable=True)
    ShippingAddress = Column(Unicode(2000), nullable=True)
    ShippingAddress2 = Column(Unicode(2000), nullable=True)
    ShippingAddress3 = Column(Unicode(2000), nullable=True)
    ShippingAddress4 = Column(Unicode(2000), nullable=True)
    ShippingAddress5 = Column(Unicode(2000), nullable=True)
    ShippingPhone = Column(Unicode(200), nullable=True)
    ShippingPhone2 = Column(Unicode(200), nullable=True)
    ShippingCity = Column(Unicode(300), nullable=True)
    ShippingPostCode = Column(Unicode(100), nullable=True)
    ShippingCountry = Column(Unicode(200), nullable=True)
    ShippingRegion = Column(Unicode(300), nullable=True)
    BillingName = Column(Unicode(300), nullable=True)
    BillingAddr = Column(Unicode(2000), nullable=True)
    BillingAddr2 = Column(Unicode(2000), nullable=True)
    BillingAddr3 = Column(Unicode(2000), nullable=True)
    BillingAddr4 = Column(Unicode(2000), nullable=True)
    BillingAddr5 = Column(Unicode(2000), nullable=True)
    BillingPhone = Column(Unicode(200), nullable=True)
    BillingPhone2 = Column(Unicode(200), nullable=True)
    BillingCity = Column(Unicode(300), nullable=True)
    BillingPostCode = Column(Unicode(100), nullable=True)
    BillingCountry = Column(Unicode(200), nullable=True)
    TaxCode = Column(Unicode(300), nullable=True)
    BranchNumber = Column(Unicode(200), nullable=True)
    TaxInvoiceRequested = Column(Unicode(100), nullable=True)
    PayMethod = Column(Unicode(300), nullable=True)
    PaidPrice = Column(Unicode(100), nullable=True)
    UnitPrice = Column(Unicode(100), nullable=True)
    SellerDiscountTotal = Column(Unicode(100), nullable=True)
    PlatformDiscountTotal = Column(Unicode(100), nullable=True)
    ShippingFee = Column(Unicode(100), nullable=True)
    WalletCredit = Column(Unicode(100), nullable=True)
    ItemName = Column(Unicode(1000), nullable=True)
    Variation = Column(Unicode(500), nullable=True)
    CdShippingProvider = Column(Unicode(300), nullable=True)
    ShippingProvider = Column(Unicode(300), nullable=True)
    ShipmentTypeName = Column(Unicode(300), nullable=True)
    ShippingProviderType = Column(Unicode(300), nullable=True)
    CdTrackingCode = Column(Unicode(300), nullable=True)
    TrackingCode = Column(Unicode(300), nullable=True)
    TrackingUrl = Column(Unicode(1000), nullable=True)
    ShippingProviderFm = Column(Unicode(300), nullable=True)
    TrackingCodeFm = Column(Unicode(300), nullable=True)
    TrackingUrlFm = Column(Unicode(1000), nullable=True)
    PromisedShippingTime = Column(Unicode(100), nullable=True)
    Premium = Column(Unicode(100), nullable=True)
    Status = Column(Unicode(300), nullable=True)
    BuyerFailedDeliveryReturnInitiator = Column(Unicode(300), nullable=True)
    BuyerFailedDeliveryReason = Column(Unicode(500), nullable=True)
    BuyerFailedDeliveryDetail = Column(Unicode(1000), nullable=True)
    BuyerFailedDeliveryUserName = Column(Unicode(300), nullable=True)
    BundleId = Column(Unicode(300), nullable=True)
    SemiManaged = Column(Unicode(100), nullable=True)
    FlexibleDeliveryTime = Column(Unicode(300), nullable=True)
    BundleDiscount = Column(Unicode(100), nullable=True)
    RefundAmount = Column(Unicode(100), nullable=True)
    SellerNote = Column(Unicode(2000), nullable=True)

    ImportFileName = Column(Unicode(500), nullable=True)
    IsNormalized = Column(Boolean, nullable=False, default=False, server_default=text("0"))
    NormalizedOn = Column(DateTime, nullable=True)
    NormalizeError = Column(Unicode(2000), nullable=True)

    isDeleted = Column(Boolean, nullable=False, default=False)
    createdBy = Column(Unicode(200), nullable=False)
    createdOn = Column(DateTime, nullable=False)
    modifiedBy = Column(Unicode(200), nullable=True)
    modifiedOn = Column(DateTime, nullable=True)

    def as_dict(self):
        return {column.name: getattr(self, column.name) for column in self.__table__.columns}
