from sqlalchemy import Boolean, Column, DateTime, Integer, Unicode, text

from config import database as db


class TiktokMaster(db.Base):
    __tablename__ = "TiktokMaster"

    TiktokMasterId = Column(Integer, primary_key=True, autoincrement=True)

    OrderId = Column(Unicode(200), nullable=True)
    OrderStatus = Column(Unicode(300), nullable=True)
    OrderSubstatus = Column(Unicode(300), nullable=True)
    CancelationReturnType = Column(Unicode(300), nullable=True)
    NormalOrPreOrder = Column(Unicode(200), nullable=True)
    SkuId = Column(Unicode(300), nullable=True)
    SellerSku = Column(Unicode(300), nullable=True)
    ProductName = Column(Unicode(1000), nullable=True)
    Variation = Column(Unicode(500), nullable=True)
    Quantity = Column(Unicode(100), nullable=True)
    SkuQuantityOfReturn = Column(Unicode(100), nullable=True)
    SkuUnitOriginalPrice = Column(Unicode(100), nullable=True)
    SkuSubtotalBeforeDiscount = Column(Unicode(100), nullable=True)
    SkuPlatformDiscount = Column(Unicode(100), nullable=True)
    SkuSellerDiscount = Column(Unicode(100), nullable=True)
    SkuSubtotalAfterDiscount = Column(Unicode(100), nullable=True)
    ShippingFeeAfterDiscount = Column(Unicode(100), nullable=True)
    OriginalShippingFee = Column(Unicode(100), nullable=True)
    ShippingFeeSellerDiscount = Column(Unicode(100), nullable=True)
    ShippingFeePlatformDiscount = Column(Unicode(100), nullable=True)
    PaymentPlatformDiscount = Column(Unicode(100), nullable=True)
    Taxes = Column(Unicode(100), nullable=True)
    OrderAmount = Column(Unicode(100), nullable=True)
    OrderRefundAmount = Column(Unicode(100), nullable=True)
    CreatedTime = Column(Unicode(100), nullable=True)
    PaidTime = Column(Unicode(100), nullable=True)
    RtsTime = Column(Unicode(100), nullable=True)
    ShippedTime = Column(Unicode(100), nullable=True)
    DeliveredTime = Column(Unicode(100), nullable=True)
    CancelledTime = Column(Unicode(100), nullable=True)
    CancelBy = Column(Unicode(300), nullable=True)
    CancelReason = Column(Unicode(1000), nullable=True)
    FulfillmentType = Column(Unicode(300), nullable=True)
    WarehouseName = Column(Unicode(300), nullable=True)
    TrackingId = Column(Unicode(300), nullable=True)
    DeliveryOption = Column(Unicode(300), nullable=True)
    ShippingProviderName = Column(Unicode(300), nullable=True)
    BuyerMessage = Column(Unicode(2000), nullable=True)
    BuyerUsername = Column(Unicode(300), nullable=True)
    Recipient = Column(Unicode(300), nullable=True)
    Phone = Column(Unicode(200), nullable=True)
    Zipcode = Column(Unicode(100), nullable=True)
    Country = Column(Unicode(200), nullable=True)
    Province = Column(Unicode(300), nullable=True)
    District = Column(Unicode(300), nullable=True)
    Districts = Column(Unicode(300), nullable=True)
    DetailAddress = Column(Unicode(2000), nullable=True)
    AdditionalAddressInformation = Column(Unicode(2000), nullable=True)
    PaymentMethod = Column(Unicode(300), nullable=True)
    WeightKg = Column(Unicode(100), nullable=True)
    ProductCategory = Column(Unicode(500), nullable=True)
    PackageId = Column(Unicode(300), nullable=True)
    SellerNote = Column(Unicode(2000), nullable=True)
    CheckedStatus = Column(Unicode(300), nullable=True)
    CheckedMarkedBy = Column(Unicode(300), nullable=True)
    RequestTaxInvoice = Column(Unicode(100), nullable=True)
    TaxInfoBuyerTaxId = Column(Unicode(300), nullable=True)
    TaxInfoType = Column(Unicode(300), nullable=True)
    TaxInfoFullNameOfBuyer = Column(Unicode(500), nullable=True)
    TaxInfoEmail = Column(Unicode(300), nullable=True)
    TaxInfoPhoneNumber = Column(Unicode(200), nullable=True)
    TaxInfoRegisteredAddress = Column(Unicode(2000), nullable=True)
    TaxInfoAddressType = Column(Unicode(300), nullable=True)

    ImportFileName = Column(Unicode(500), nullable=True)
    IsNormalized = Column(Boolean, nullable=False, default=False, server_default=text("0"))
    NormalizedOn = Column(DateTime, nullable=True)
    NormalizeError = Column(Unicode(2000), nullable=True)

    isDeleted = Column(Boolean, nullable=False, default=False)
    createdBy = Column(Unicode(200), nullable=False)
    createdOn = Column(DateTime, nullable=False)
    modifiedBy = Column(Unicode(200), nullable=True)
    modifiedOn = Column(DateTime, nullable=True)

    def as_dict(self):
        return {column.name: getattr(self, column.name) for column in self.__table__.columns}
